### ISSUE TITLE
No mines

### ISSUE THREAD

**Issue by fatadel** [se2p/ps-wise-2021-program-description#11]
The description states 

> Valid boards must have more than one square, and do not contain only mines.

However, what if no mine is given at all? Is that considered an invalid configuration as well?

**Comment by UzunerH** [comment]
I would guess if there is no mine given, we can just make the player win with a completely revealed and empty board after the first valid input. But of course I am also fine with just saying there must be at least one bomb... which would result in the same most of the time (except the player clicks on exactly one of the adjacent fields, which are all 1's)

I personally would prefer the former handling ( I.e. just letting the player win after the first input), since it is easier :)
But in the end, please Dr. Gambi, clarify this, since it defines the configuration parsing process.

**Comment by alessiogambi** [comment]
@UzunerH I also would say that a game with no mines corresponds that the game that is automatically won after the first move.
