### ISSUE TITLE
Clarify some points of Minesweeper

### ISSUE THREAD

**Issue by apouam01** [se2p/ps-wise-2021-program-description#12]
Dear All

I have some concern about the game. and i would like to get some clarification on the following points.
1. in the sake of vocabulary clarification, is there any difference between the term block and square use in the description ? 
2. What is the maximum  size of board that can be supported by the application ?
3. must we have only one mine regardless of the size of the board?  in the example with (3x3) size board , it is state that we     should have only one mine. is it alsi the case for any (nxm) size board ?
4. how to know if by uncovering a block we have to display a number or nothing. For example if i click a no-mine square and there is a mine after 2, 3 ... squares on it, how to know that i hav to display 2, 3   or nothing  in the uncovered block?
5. When playing the Game if i uncover a blank square how many square adjacent to it  have to be automatically uncovered ? this question is relative to the example of the program description where the won game is played (almost at the end of the program description page). the first square (upper left corner) is clicked(corresponds to inputs  ``1`` ``1`` R), then suddently i see almost all block of the Game uncovered, except the block containing mine. Can you clarify please step by step what happen ? precisely I expected that only the squares with coordinates (1, 2),(2,1), (2,2) directly adjacent to square (1,1) would be uncovered. why the square (2,3) ,(3,1) , (3,2),(3,3) have been uncovered too during this process? Is it a recursive operation? i mean for example. because (2,1) is uncovered, all adjacent block on it not containing a mine have to be uncovered too.
6. in the real game, wherever on the board you click for the first time or first click (whether on a mine or not) this must not end the Game. should this behavior be respected. if yes I would like to propose a test for       this case or scenario if not exist. ( I saw your example in the program description where clicking on the mine ends the game but i don't know if this should happen for the first click during Game start)
7. how many lines are there between the message banner and the board ?  between the message banner  and the input console ?
8. Where exactly the configuration files have to be placed?
9.if I understood correctly, each test case will correspond to one configuration file. since during the test one file is passed as parameter to the console. how we have to interact with differents configuration files during the test ? I mean how to point to the right file during each test case?  

 
it's enough for today. the other questions will come probably later

kinds Regards
Abdel Aziz

**Comment by UzunerH** [comment]
Hi,

Following is my understanding regarding your points:

1. No difference, they are the same
2. Good question. MAX_INT? (Or how it is called...?) 
3. I think in general there is no limit on bombs on one field. One question would be if we want to only allow boards with at least one square not a bomb, as otherwise the game would instantly end before the first user input as a lost game. EDIT: just saw that only bombs is not permitted, so I guess that your field can basically contain anything between 0 and n*m-1  bombs (where n and m are length and width of the field). 0 bombs would result in an empty board and win after first valid player input while n*m-1 bombs would be very hard and pretty much random to solve.
4. The number does not show how far away the next bomb is, but rather how many of the 8 adjacent blocks contain a bomb. So the block always contains the number of bombs adjacent to that block and is empty if all 8 adjacent blocks are no bombs.
5. If you uncover a block and it is empty that means ALL adjacent blocks are no bombs. Therefore all of them can be safely uncovered by the player, which is just done automatically as a quality of life service. If during this process another empty block is uncovered, the process is repeated for all adjacent blocks of that one too, and so on
6. I think this question was asked and answered somewhere (maybe during the exercise, I don't remember exactly) and I think we agreed that this functionality was too complex to be included. Please correct me if I am wrong.
7. No empty lines between.
8. As far as I see it, there is no specification on that. Therefore any directory should work. I guess the program just takes as the argument the absolute path to the config file... again, not sure, this is how I solved it until now. Please correct me if I am wrong.
9. I think during the test we are supposed to mock the data, I.e. use the temporary files and mock the content directly in the test class, see the BasicTest.java file for an example. There is no need for *.cfg files for tests.

Regarding your next questions, bring it on :)

Best Regards
Hakan
