### ISSUE TITLE
Disagreement with the new additions

### ISSUE THREAD

**Issue by fatadel** [se2p/ps-wise-2021-program-description#30]
> However, if the standard input is closed (for example, because we are testing the program); then, the program should end showing the following message:
> 
> Not enough inputs!
> 
> Note: the behavior in this case is exactly the same as the win or lost game, except for the message displayed in the banner.

I completely disagree with this.
First of all, may we please stick to the original assignment specification and only add some clarification points.
It's very frustrating that the specification is always changing.
And I also think it is unfair to introduce an assignment and then change its requirements up until the latest days of the deadline.
Regarding the statement itself, why ever the standard input should be closed if the game is not finished?

**Comment by fatadel** [comment]
Okay, the question is clarified and that was pretty easy to implement.
But, @alessiogambi, please stop adding new requirements to the program specification! :D

**Comment by alessiogambi** [comment]
@fatadel I am sorry about the frustration/fuzz around this, but just to be fair: We are **not** introducing new requirements, we are **only** refining the specifications of the program after clarifying some points that may cause issues later (i.e., during grading). This is the expected process, it is described in the slides, and we discussed it in the exercise sessions. 

Few final considerations:

* This process of improvements/clarifications/updates is necessary only at the beginning, when specifications might be brittle, and will be over soon. The positive effects of this should be visible soon, as fewer to none students will fail public tests because of "unclear specifications."
* The first assignment is purposely made easier (free flow and monolithic styles are not that complex!) exactly to lower the burden on the students and balance this initial warm-up phase of specification requirements
* The students, like yourself, that have spent time and effort to improve and contribute will be rewarded, so you did not only good to the class, but also to yourself
